### ISSUE TITLE
Design

### ISSUE THREAD

**Issue by annikavennemann** [annikavennemann/capstone-project#1]
## Value statement - a requirement, not a solution
As a user I want to have a modern design so that I enjoy using the app.
 
## Description (Text, Scribble, Wireframe, Design)
- using Adobe Xd

## Acceptance criteria
- [x] using fonts and colours of YAA

## Tasks
- [x] define the styleguide
- [x] checkout modern app-designs
- [x] build the mockup within adobe Xd - Login, Register, Welcome-Page, Checklist
- [x] feedback-loop with Sascha & Sarah
- [x] implement feedback

## Size
medium
