### ISSUE TITLE
Style Registration and Login Page

### ISSUE THREAD

**Issue by annikavennemann** [annikavennemann/capstone-project#10]
## Value statement 
As a user I want to have a positive first impression when opening the App, so that the style lays within the CD.

## Description
- Use Styleguidist to organise the style

## Acceptance criteria
- [x] the style matches the feedbacked prototype

## Tasks
- [x] component registration-style
- [x] component login-style

## Size
M
