### ISSUE TITLE
Create Entity-Relations

### ISSUE THREAD

**Issue by annikavennemann** [annikavennemann/capstone-project#11]
## Value statement 
As a user I want to have access to my own checklist

## Description
Create a relation between the User- and Checklist Entities

## Acceptance criteria
- [x] each User hat One Checklist

## Tasks
- [x] research the group attribute for different checklist-types
- [x] Token and User mit manyToOne verbinden
- [x] connect the tables via UserChecklist by "one to many"

## Size
S
