### ISSUE TITLE
Secure Password through validation

### ISSUE THREAD

**Issue by annikavennemann** [annikavennemann/capstone-project#13]
## Value statement
As a user I want to have a secure password

## Description
- Write password validations and inform the user if he has to create another password
- ask a second time for the password and compare them

## Acceptance criteria
- [ ] user need to provide a username (Ohhh-e-mail), first and last name with no more than 255 symbols
- [ ] Password can not be smaller than 8 symbols and maximum of 25 symbols with the following requirements: Using minimum one Capital letter, Using minimum one small letter, Using minimum one Number,  Using at least one Special symbols
- [ ] User has to agree to the Terms and Conditions by checkbox before being able to submit the input, if not he is not able to submit the data

## Tasks
- [ ] write validation-functions

## Size
M
