### ISSUE TITLE
validate Token within login

### ISSUE THREAD

**Issue by annikavennemann** [annikavennemann/capstone-project#19]
## Value statement 
As a user I want to have secure access to my personal onboarding-app, which is why I need a token that is validated by switching to another page.

## Description
Post the token in request-header from FE to BE, where the token is validated. If isValid == true, send user to welcome-Page

## Acceptance criteria
- [x] The user gets access to the welcome page if the password is correct.

## Tasks
- [x] Write fetch with post-method in frontend
- [x] Write the validation-method in backend
- [x] Post response to FE for giving the user access to the next page

## Size
Medium
