### ISSUE TITLE
Fetch Personal Checklist in FE

### ISSUE THREAD

**Issue by annikavennemann** [annikavennemann/capstone-project#32]
## Acceptance criteria
- [x] each User has access to his own checklist

## Tasks
- [x] write fetch in frontend
- [x] style checklist-page

## Size
S
