### ISSUE TITLE
User registration

### ISSUE THREAD

**Issue by annikavennemann** [annikavennemann/capstone-project#4]
## Value statement - a requirement, not a solution
As a user I need to have a unique account (user-name and password) to login into the app.

## Description
- Before using the app for the first time, each employee needs to register with the business email address.

## Acceptance criteria
- [x] the userData is saved within the database

## Tasks
- [x] frontend: build a registration-form
- [x] implement the security-token
- [x] post data to backend
- [x] backend: save data within database

## Size
medium
