### ISSUE TITLE
Secure Login

### ISSUE THREAD

**Issue by annikavennemann** [annikavennemann/capstone-project#5]
## Value statement - a requirement, not a solution
As a user I want to use the app with my registered account, so that I have access to my personal onboarding-app.

## Description
![Wireframe_Login_OnboardingApp](https://user-images.githubusercontent.com/72032396/99791280-b2e3f400-2b25-11eb-9851-bc3998683bbc.png)

## Acceptance criteria
- [x] if username and password are correct allow login -> send user to home-page

## Tasks
- [x] write onSubmit function to post the userData to backend
- [x] create Token in backend for each post-request of userData
- [x] if token is valid, the user can go start using the app

## Size
M
