### ISSUE TITLE
Building the Main-Page-frontend

### ISSUE THREAD

**Issue by annikavennemann** [annikavennemann/capstone-project#7]
## Value statement - a requirement, not a solution
As a user I want to get a good overview on the app-content and how I am supposed to use the app.

## Description
![Wireframe_MainPage_OnboardingApp](https://user-images.githubusercontent.com/72032396/99796732-4a4d4500-2b2e-11eb-92ac-c6aedcc4cb78.png)

## Acceptance criteria
- [x] play the video
- [x] the user knows what will happen next
- [x] slide the core-values

## Tasks
- [x] personal welcome
- [x] display video
- [x] core-value-gallery
- [x] way of working
- [x] next: Checklist

## Size
L
