### ISSUE TITLE
Collect content for the welcome-page

### ISSUE THREAD

**Issue by annikavennemann** [annikavennemann/capstone-project#8]
## Value statement 
As a user I want to get a great overview about the represented company as well as the advantages of the used app.

## Tasks
- [x] brainstorm with P&C: Checklist
- [x] use yaa-pictures
- [x] content examples: "Who we aspire to be"

## Size
S
